### ISSUE TITLE
Incorrect update interval

### ISSUE THREAD

**Issue by yellow8-vom** [DrustZ/VelocityDetector#1]
Great example!
There are small errors in the code:

- deviceMotionUpdateInterval should be used instead of acceleromaterUpdateInterval, since the deviceMotion (sensor-fusioned data) is used
- I don't exactly understand why gravity is added to userAcceleration, since gravity is already compensated in the userAcceleration data.

**Comment by DrustZ** [comment]
Thanks Yellow!

This project is frankly too long ago and I cannot redraw my memory on that --- maybe there're some small mistakes in the implementation. Feel free to correct them if you think makes sense! Also the sdk I developed was around iOS 8 so there might be some significant change of the api contents.
